### ISSUE TITLE
Letters 'i' and 'I' in the comments rendering like 'l'

### ISSUE THREAD

**Issue by ndrwrbgs** [plantuml/plantuml-server#167]
> Found a strange bug: in some cases 'i' and 'I'(uppercase i) rendering as lowercase L.
> 
> ```wsd
> @startuml
> Bob -> Alice: Hi
> @enduml
> ```
> 
> ![image](https://user-images.githubusercontent.com/888475/59711386-57645700-920b-11e9-81eb-f978fb07c94a.png)
> 
> 'i' redndering as 'i' only in combination with some other letters in the same word. Also length of the comment plays role.
> 
> ```wsd
> @startuml
> Bob -> Alice: iI
> Bob -> Alice: iIl
> Bob -> Alice: iIln
> Bob -> Alice: iIlne
> @enduml
> ```
> 
> ![image](https://user-images.githubusercontent.com/888475/59712909-7d3f2b00-920e-11e9-9ba5-93f8c3259f3d.png)
> 
> Visual Studio Code - Insiders
> Version: 1.36.0-insider (user setup)
> Commit: 7f53e50cbf316dff94fbbe5406d8f352dac99a6b
> Date: 2019-06-18T11:41:31.168Z
> Electron: 4.2.4
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.18362

**Comment by ndrwrbgs** [comment]
Migration from https://github.com/qjebbs/vscode-plantuml/issues/240

**Comment by arnaudroques** [comment]
This is a really strange issue.
It looks like a font issue.
It is working fine on the online server http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKl38v798pKi1oW00

[Could you try](http://www.plantuml.com/plantuml/uml/oyaiBadBpojHyCW40000):
```
@startuml
listfont Hi
@enduml
```

And tell us the result ?

**Comment by ndrwrbgs** [comment]
![image](https://user-images.githubusercontent.com/10776890/103432020-f5b9d280-4b8d-11eb-9f44-651811927dc0.png)

**Comment by ndrwrbgs** [comment]
My result is probably useless now though, since it looks like my repro isn't reproing!
@alexzaitzev for if they still have a repro (looks like I might not be able to tag them!)

**Comment by ndrwrbgs** [comment]
Is there any code in this jar that keeps cross-rendering state that might explain it? E.g., was some complicated thing like "if you render X then all requests after that until a restart could do Y" or is that impossible from how it's structured?

**Comment by OleBae** [comment]
I am seeing this as well. I using 'docker run -d -p 8080:8080 plantuml/plantuml-server:jetty' on windows (wsl2), pulled down earlier today. 

Investigating a bit further it seems it is an SVG problem (also on plantuml.com). Using 
@startuml
bob -> alice: hei, i, aziz
@enduml

I get the correct rendering http://www.plantuml.com/plantuml/png/SoWkIImgAStDuKhAJrBGjLD8pCbCJhLIo4ZDr540eiIgp2ekXzIy5A0I0000
![image](https://user-images.githubusercontent.com/31850671/103558348-d0420700-4eb4-11eb-996a-a4054a71f5b0.png)

But switching to SVG view http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuKhAJrBGjLD8pCbCJhLIo4ZDr540eiIgp2ekXzIy5A0I0000
I get upper case I
![image](https://user-images.githubusercontent.com/31850671/103558484-097a7700-4eb5-11eb-983a-14c84923930f.png)

Verified this behavior also when using localhost:8080, so I guess the Visual Studio Code plantuml /markdown integration uses SVG (or some other non-png image format with the same problem).

**Comment by OleBae** [comment]
Thinking a bit more about this I realized that with SVG it would be rendered on my system. Looking at the svg page-source I see that the lower case i **is** passed correctly. However it looks upper case on chrome, edge and firefox.

Testing with a local save, changing font-size="13" to font-size="14" (as in "alice") makes it look lower case. Testing on my other computer it looks ok, but changing the display scaling from 125% to 100% makes it look upper case! 

So I guess for font-size 13 the font that is used to render i looks like l with 100% scaling on windows? I would check which font is used, but I have no idea how (and google wants to tell me about svg fonts...) But using font-family="arial" makes no difference in how it looks, so presumably that is the font that have the problem. Changing  font-family to some other font makes the problem go away. 

So, not a problem with plantuml-server! But if this is a problem with all browsers on a fairly standard windows system, perhaps avoid font-size 13 anyway? 

Both my computers are up to date windows 10, one only a few weeks old, the other a few years.

**Comment by ndrwrbgs** [comment]
Ole, are you able to repro it with varying amounts of i's? The hypothesis
above makes sense to me up until that behavior point, I'm not familiar with
latin-based fonts changing their behavior based the content of the text -
this is what got me thinking the font itself had to be being given
different input.

**Comment by OleBae** [comment]
@ndrwrbgs yes, I have tried different amounts of i; all of them turn into I.
![image](https://user-images.githubusercontent.com/31850671/103634407-4bec9400-4f47-11eb-9439-70f0c04e168c.png)
That said there are a few cases where the i look ok, see below.


Note that this is not really an issue with the font itself - it looks just fine on the laptop with 125% scaling! It is a font rendering issue where for that particular size, font and display scaling. Probably together with the placement algorithm in the svg-render? The white pixel between the lower and upper part of the i is "lost". I would not be surprised if this was affected by other stuff as well like the display type or  the placement of content in relation to other content. 

I actually wonder if I am seeing something like that. Because when I experiment a bit I get that this
@startuml
Bob -> Alice: T, i, Onei, iI
@enduml
looks good (lower case), while the below (only change added 'w')
@startuml
Bob -> Alice: Tw, i, Onei, iI
@enduml
looks upper case!

For me the cases where i looks OK are rare. Others may have this as the normal case?

Btw I also changed the zoom level in Chrome. The problem is only present at 100% - for all other levels it looks good!

**Comment by arnaudroques** [comment]
Could you try to edit the SVG source and remove the `lengthAdjust="spacingAndGlyphs"` attributes we use ?
I am wondering if this could have an impact on this strange behavior.

**Comment by OleBae** [comment]
@arnaudroques Removed lengthAdjust and that fixed it, at least for that one example. 
![image](https://user-images.githubusercontent.com/31850671/103639478-b5bc6c00-4f4e-11eb-8f1e-3538efba0720.png)
lengthAdjust="spacing" also works fine.

The complexities involved in this seemingly trivial problem is fascinating, in its own way.

**Comment by arnaudroques** [comment]
> The complexities involved in this seemingly trivial problem is fascinating, in its own way.

Fascinating and funny!

I am afraid that changing `lengthAdjust="spacingAndGlyphs"` to `lengthAdjust="spacing"` will have some unexpected impact.
Not sure about the right solution...

Since we are doing strange things, could you try to add [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) just to the the result:

`<text fill="#000000" font-family="sans-serif" font-size="13" lengthAdjust="spacingAndGlyphs" textLength="36" x="35.5" y="66.3638">​i&#8203;​i​&#8203;i&#8203;​i&#8203;​i​&#8203;i&#8203;​i​&#8203;i​&#8203;i​&#8203;i&#8203;​i​&#8203;i</text>`

**Comment by OleBae** [comment]
Here is the result of that:
![image](https://user-images.githubusercontent.com/31850671/103643584-3d0cde00-4f55-11eb-85b2-e27e6372f6f5.png)

What is the reason for having lengthAdjust in the first place?

If changing/removing lengthAdjust could have unexpected impacts, then perhaps going down to size 12 or up to size 14 is an option? Or putting some exists-on-windows-font ahead of the sans-serif like font-family="calibri, sans-serif". Though I am sure people that care about fonts, would be horrified by having different fonts, so that needs to be a global change.

**Comment by arnaudroques** [comment]
> What is the reason for having lengthAdjust in the first place?

It's a long story, [explained here](https://forum.plantuml.net/3182/differently-produced-building-different-platforms-consistent).

Extract:

> We are facing here a severe issue with text and SVG.
> 
> When PlantUML is doing its drawing, it must know the exact dimension of texts, to be able to draw appropriate boxes (for example) around texts.
> 
> Under PNG, everything is fine.
> 
> Using SVG, it's another story, because the text drawing will be interpreted latter on the SVG client, and depending on fonts installed on each client, the text may be rendered differently. To force the SVG client to use a specific dimension for the text, we use the textLenght attribute, so that boxes fit the text.
> 

We've just updated the online webserver (and also last beta http://beta.plantuml.net/plantuml.jar) to use `lengthAdjust="spacing"` now.
We'll see the result...

**Comment by OleBae** [comment]
So that does fix the i problem! In my relatively simple ongoing work there are some differences, in particular the autonumbering is less streched / more space (which I think looks better) and the rt=1234 has more space, which I find no worse and possibly better. The one thing that does not turn out so well is the bold "not" in about the middle of the diagram. 
![image](https://user-images.githubusercontent.com/31850671/103665379-a56ab800-4f73-11eb-9f55-4a3b92d9d360.png)
Looking at these pre-fix and post-fix diagrams side by side it seems the spacingAndGlyphs stretches the characters in both dimensions which sort of the explains how it could cause this kind of problem. 

Since I was curious I also made a font-size=14 variant and rendered that locally. I think that is more similar than the =spacing one, possibly because many of the fonts are already often a tiny bit larger than their "13" size when =spacingAndGlyphs are used? 
![image](https://user-images.githubusercontent.com/31850671/103666930-8f5df700-4f75-11eb-8e3a-138969780fca.png)
(Url for the examples above http://www.plantuml.com/plantuml/svg/dLHDQzj04BtlhnXyieqYzEKIXzIaDMdfeOv1a4kImtgriHQqkqAxKjf_tz6NiQWbS4uBE_FUpBnvp8EnjB2bp83GqcfLoWClO7P_sBnudlSs8pc61HCvLHQ-b-R7xnYeWLdzRh_jXd7yZ8kgZrlzQ_-g32z4nVYCC9rbd5cXbG6M2Qwi8TqBDviEUmTR7sYIvEeut_lEOxmWgTAMWwwmhIxz3X8Balu1tv2k91ASWlXrNzYlGR3o7DZxSwLlAfgLt07yzHORqX0MufZQKzMTjf1m9XAUGAe_m6emN2MWD2JKKfUGRlQpJf7wsH_qrqVgwj7A6y44evWLOYv94fn9yhHTa0kAjCImN69ikQoRjqwzY6PoI3GtE8i5bb9rvExLdNt1pbptQbpe8svaWUjL8AVs5mPUuBJqJi_LBsz8LcU2C625v6XdcOD-Xu-KgvggsL-Z1sW5iipGhTJOLrNp_OVQ_znXIIWuuw92Bnp-GkTaf2WgmJYvMeDmr0dXAAPspuGqgwYrzdFezEcNfOdhkTUUD43VBGRQggVv9dOwsblaNpzF57m2ymdTecZARxUJVekYzUsvgD6PgCDZyHX3cQEjU6khZDRApfcMU0lHCtWxw07BGoBeiQ1o0NW5XM8SXC9CoV4ViKCMjrd50zuSlCN_0000)

**Comment by arnaudroques** [comment]
Ok, thanks for your detailed tests, it really helps.

We have already pushed a new version on the online server (and a new beta http://beta.plantuml.net/plantuml.jar )
On second though, we propose that the user may choose its own strategy.
So now you can use in your diagram text either:
```
skinparam lengthAdjust spacing
skinparam lengthAdjust none
skinparam lengthAdjust spacingAndGlyphs
```
By default, the strategy is `spacing`. You can change it so see the difference.

About bold management, we realize that we could take advantage of the [tspan](http://tutorials.jenkov.com/svg/tspan-element.html) tag in SVG. This will greatly improve bold and italic text placement in SVG.
Unfortunately, this is not an easy change to implement, because it really changes the way we handle texts in all formats (PNG, EPS...).

We'll post a message here when we will have implement it.

**Comment by OleBae** [comment]
And thank **you** for fixing this, and more in general for plantUML which is great!

Btw I don't find _anything_ about the docker image I am using. If one already have docker installed that seems the easiest way to "install" it so perhaps it should have a section on your homepage? (Of course I may have missed something.) Is the docker image reflecting the online version, so that there is already a newer version available?

**Comment by alexzaitzev** [comment]
Thank you guys for fixing it! I am delighted to see how a small bug that I found led to such thoughtful discussion and investigations. Even though it was not actually plantuml problem, it's really great that it was fixed.

I am using local plantuml on tomcat without docker and I can confirm that after updating library 'i' problem was solved.

Before:
![before](https://user-images.githubusercontent.com/888475/111986687-93c69480-8b0e-11eb-95f7-4b4b58287668.png)

After:
![after](https://user-images.githubusercontent.com/888475/111986691-945f2b00-8b0e-11eb-86db-db4521f6bdb6.png)
