### ISSUE TITLE
Docker and how to use !include %getenv("XYZ")

### ISSUE THREAD

**Issue by skelutten** [plantuml/plantuml-server#172]
Since Markdown/PLantUML preview in VSCode now unfortunately requires a plantuml server, I've run into problems on how to get things working with PlantUML Server in Docker.

Lines like this:
!include %getenv("XYZ_1")
Gives errors like
"cannot include".
Replacing it with the real file name works after some tweaking.

After some Googling I thought this should work:
sudo docker run -d -p 8080:8080 -v /xyz:/xyz -v /otherpath:/otherpath -e XYZ_1=/xyz/abcd/xyz_1.txt -e XYZ_2=/otherpath/cdef/stdmacros.txt  plantuml/plantuml-server:jetty

But it doesn't.
So how are you supposed to make PlantUML server recognize these kind of env variables and paths to make PlantUML work?

/D

**Comment by HeinrichAD** [comment]
This should now be done with version 1.2023.9

- You can access any environment variable starting with `PLANTUML` as prefix except variables starting with `plantuml.security` any time.
- You can access all environment variables if the `PLANTUML_SECURITY_PROFILE` is set to `UNSECURE`.
- Likewise, `%dirpath()` will also only return a value if `PLANTUML_SECURITY_PROFILE` is set to `UNSECURE`. Otherwise it will always be empty.
- It is also possible to include a file over an env variable e.g. `!include %getenv("PLANTUML_INCLUDE_TEMPLATE_1")` if the `plantuml.allowlist.path` is set appropriately. Also see <https://plantuml.com/security>.

Therefore, this issue can now be closed.
