### ISSUE TITLE
NGINX config to server static diagrams for inclusion into others

### ISSUE THREAD

**Issue by CyberSeppi** [plantuml/plantuml-server#202]
Hi there,

I set up an nginx which should serve static files (diagrams in my case) that can be included into others like 

!include https://......

The thing is, that it doesn´t work.
It works with, e.g 
https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

The difference are the META of the http response, and that favicon.ico, which I had to "dummy" (just return 200 without content)

![image](https://user-images.githubusercontent.com/53782896/141956367-6ac8afab-a301-4291-ace5-d28b3a341cd8.png)

Can you tell me how to set up the response to make it working ?

Thanks and Greetings,

Julian

**Comment by HeinrichAD** [comment]
If I have to guess, I think the problem is that an `!include http://localhost` or `!include http://plantuml-server`, at the time of fetching the diagram, points to itself (PlantUML Server) and not to the Nginx server.

----

The following situation is working for me:

I modified the [Nginx reverse proxy example with defined location directive (different context path)](https://github.com/plantuml/plantuml-server/blob/master/examples/nginx-contextpath).

What I did:
1. create the following test diagram `nginx-contextpath/diagrams/test.puml`:
    ```plantuml
    Alice -> Bob : "I am from another file"
    ```
2. add the new folder inside the Nginx server as an additional docker volume:
    ```diff
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
    +     - ./diagrams:/www/diagrams:ro
    ```
3. tell Nginx (`nginx.conf`) to server (static) the newly added directory
    ```diff
    http {
    +    # OPTIONAL  (It work for me with and without it)
    +    types {
    +        text/plain   puml;
    +    }
    
        server {
            listen          80;
            server_name     localhost;
    +       root /www;
    
            # PlantUML
            location /plantuml/ {
                proxy_pass http://plantuml-server:8080/plantuml/;
            }
        }
    # ...
    ```
4. try it
    1. start Nginx + PlantUML Server: `docker compose up -d` (see example README)
    2. go to: <http://localhost/plantuml>
    3. enter diagram code
        ```plantuml
        @startuml
        !include http://nginx/diagrams/test.puml
        Bob -> Alice : hello
        @enduml
        ```
    **NOTE**: I used `!include http://nginx/diagrams/test.puml` and not `localhost`! The reason is fairly simple, at the time when the PlantUML Server tries to fetch the diagram from `localhost`, `localhost` does not point to the Nginx server but to the PlantUML Server itself.
5. see result
![image](https://github.com/plantuml/plantuml-server/assets/5962361/c67c9228-feb6-47d6-89f0-a5a72dce0d6f)
