### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by JRGit4UE** [plantuml/plantuml-server#210]
On 
- Ubuntu 20.04
- Docker 20.10.5
- Maven 3.6.3
with successful build via `mvn package`
I get an error building the docker image `docker image build -f Dockerfile.jetty -t plantuml-server:local .`

```
[ERROR] Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-checkstyle-plugin:jar:3.1.2: Could not transfer artifact org.apache.maven.plugins:maven-checkstyle-plugin:pom:3.1.2 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-checkstyle-plugin/3.1.2/maven-checkstyle-plugin-3.1.2.pom: Unknown host repo.maven.apache.org: Temporary failure in name resolution -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
The command '/bin/sh -c mvn --batch-mode --define java.net.useSystemProxies=true package' returned a non-zero code: 1
```

I have removed the .m2 dir and rebuilt everything, the error is still the same.
Maybe someone can help?

Thx in advance

**Comment by HeinrichAD** [comment]
Since the error message states `Unknown host repo.maven.apache.org: Temporary failure in name resolution`, it could be a DNS problem. Maybe the DNS server is not reachable/responding or the company DNS reject to resolve this due to specific rules.
You could try to use an open DNS to test if your current DNS is the problem. (If you are allowed to do this.)

Other possible reason could be: using a proxy,  firewall rules, company runs own Maven repository, local Maven settings (~/.m2/settings.xml) are corrupted.
