### ISSUE TITLE
rocket emoji causes UnsupportedOperationException

### ISSUE THREAD

**Issue by VladimirAlexiev** [plantuml/plantuml-server#231]
(A bit related to https://github.com/plantuml/plantuml-server/issues/32, which should really be in this project).

On a whim I tried a `rocket` emoji (Eg see https://emojipedia.org/rocket/)
```
usecase "<:rocket:> Implement the changes" as Implement
[Company] --> Implement
```
at [plantuml server](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIejJarEB4vLKBAnAifFpaujiR9JyCmjo4dDJSqhKIZ9I5L8paZCIqyjLb98B4R8S4Kxv-SM9EPLnYhewjeXYJkavgK0pGK0) causes this scary-looking result (cc @arnaudroques):

![image](https://user-images.githubusercontent.com/536250/173383871-03accf24-0cc5-4da5-a3af-75a30c9aa399.png)

In contrast, a wrong emoji name (eg `<:nosuch:>`) is rendered as that same name.

It's strange that if I use the image URL directly in this issue (or a code block surrounded with `@startuml..@enduml`), it shows `<:rocket:>`! I guess that's because Github invokes the plantuml server in a slightly different way?

The image URL is:
`http://www.plantuml.com/plantuml/png/SoWkIImgAStDuIejJarEB4vLKBAnAifFpaujiR9JyCmjo4dDJSqhKIZ9I5L8paZCIqyjLb98B4R8S4Kxv-SM9EPLnYhewjeXYJkavgK0pGK0`

**Comment by HeinrichAD** [comment]
The bug seems to be fixed. I can not reproduce it with the current version `1.2023.8`.

(But, I could reproduce the issue with version `1.2022.6` as stated in the error image.)

<details><summary>Result with current version</summary>

```plantuml
@startuml
usecase "<:rocket:> Implement the changes" as Implement
[Company] --> Implement
@enduml
```

![image](https://github.com/plantuml/plantuml-server/assets/5962361/950d8dd8-1c9f-4d53-8816-b589edb75661)

</details>
