### ISSUE TITLE
plantuml-server error

### ISSUE THREAD

**Issue by linbaobei** [plantuml/plantuml-server#241]
centos7
tomcat 10 
jdk11

Sorry, but things didn't work out as planned.

Wed Oct 05 12:34:24 CST 2022
Request that failed: /plantuml-jsp-v1.2022.7/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
Status code: 500
Exception: org.apache.jasper.JasperException: /index.jsp (行.: [52], 列: [13]) 文.件[resource/githubribbon.html] 未找到

**Comment by HeinrichAD** [comment]
To be honest, with so little information, it's hard to provide the right answer.

If I interpret it correctly, PlantUML Server was deployed as a "war" file on a Tomcat server. Thereby the "war" file `plantuml-jsp-v1.2022.7.war` was taken from the release section.

First, since you are deploying to a Tomcat server the `jsp` version is the right choice. Second, since you are using Tomcat 10 and JDK 11 it is also correct not to chose the `jdk8` version. (As a tip, it is nicer to rename the file from `plantuml-jsp-v1.2022.7.war` to `plantuml.war` during deployment.)

The actual error message is that the file `resource/githubribbon.html` cannot be found. Here I can only think of the following possibilities:
- the file was deleted manually
- `plantuml-jsp-v1.2022.7.war` was built incorrectly

Could you please check if the error still exists with the current version? Also, more information would be useful to provide further help.
