### ISSUE TITLE
Plantuml.com images generate as webp not png

### ISSUE THREAD

**Issue by jneis-at-hilscher** [plantuml/plantuml-server#255]
Today I encountered an issue with PNG images generated using the online server.

I generated the image by using the PlantUML VSCode extension.
I selected "PNG" as output type and the file saved with a .png extension.
When importing the generated image into a LaTeX document using \includegraphics{} I get an error from libpng stating that the image is not a PNG.

When attempting to manually generate the image it appears that all PNG images are generated as webp now.
This can be replicated as follows:

- Open the Online Server from the official PlantUML website
- Click the "PNG" to convert the default diagram into a PNG image
- Right click the generated image and attempt to save the image
- The image will save with a .webp extension

I could not find any documentation of this change and would ask that it is reverted as it potentially breaks anything relying on PNG files as webp is not a drop-in replacement.

This issue seems related to #254 

A workaround for now is opening the image with GIMP and saving it as PNG again.

**Comment by arnaudroques** [comment]
Ok, we've set up a temporary workaround which should just work.
Can you try and tell us?
Thanks!

**Comment by svermaji** [comment]
Hi Team - I just tried and still plantuml is saving as webp.  Even png option is saving image as webp.

**Comment by arnaudroques** [comment]
I know this is strange, but if you use URL from **outside** our webserver, you got PNG.
For example, try to save this: https://www.plantuml.com/plantuml/png/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiWiLYZ90185UUdsN0wfUIb0DG00 and you'll get PNG.

However, if you go to our webserver directly with the very same data: https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuNBAJrBGjLDmpCbCJbMmKiWiLYZ90185UUdsN0wfUIb0DG00 you'll get WEBP.

Since plugins (as PlantUML VSCode extension) directly generate URL, they should get PNG (tell me if I'm wrong), so they should work.

Does it help?

**Comment by svermaji** [comment]
Thanks for suggestion.  It is not working when I am trying same or nearby tab on Edge/Chrome.  But if I copy png url and try on incognito window, its working.  This can be used as workaround.  Thanks
