### ISSUE TITLE
Exporting a diagram of type MAP creates an empty file

### ISSUE THREAD

**Issue by voidek** [plantuml/plantuml-server#310]
**Describe the bug**
Exporting a diagram of type MAP creates an empty file,
both through the use of the gui or via the endpoint by sending 'plantuml/map/ENCODED'
like stated in https://plantuml.com/de/server

**To Reproduce**

1. Hover Over The Bar Icon
2. Click on 'Export diagram'
3. Choose 'MAP' as Diagram type
4. Click 'Export'
5. Open the downloaded file
4. See error (empty file)

**Expected behavior**
The output file should not be empty and contain a structure as stated https://plantuml.com/de/server
`<map id="plantuml_map" name="plantuml_map">
<area shape="rect" id="id1" href="http://forum.plantuml.net" title="http://forum.plantuml.net" alt="" coords="38,50,199,65"/>
<area shape="rect" id="id2" href="http://plantuml.com" title="http://plantuml.com" alt="" coords="8,3,50,116"/>
</map>`

**Screenshots**
![image](https://github.com/plantuml/plantuml-server/assets/49061972/d3ddea34-b82d-4259-9d0f-ce622a599691)

**Setup**
- Docker Container with plantuml-server:v1.2023.10
- Browser [Chrome]

**Comment by HeinrichAD** [comment]
Please note that you have to use an appropriate PlantUML code for this feature. Code that does not use the map features at all will (understandably) result in an empty map.

In the background of the attached image I can see that the used code does not use the map features, since the fifth button for the map in the upper right corner is not displayed. I suspect at this point that you have used the standard `Bob -> Alice : hello` example.

Tip: Use the code example from the documentation you linked. After that you should be able to see something.

----

### No map example
![no-map-example](https://github.com/plantuml/plantuml-server/assets/5962361/894bdef3-629c-4fe8-ac47-704b0d579dce)


### Map example
Please note: here
1. the Map button is shown,
2. the link inside the image is clickable.

![map-example](https://github.com/plantuml/plantuml-server/assets/5962361/823eaded-9676-4455-a185-406b196e8b8f)
