### ISSUE TITLE
Auto-submit

### ISSUE THREAD

**Issue by wernight** [plantuml/plantuml-server#44]
Currently one needs to press Submit to see the result. This even break undo history.

I'd suggest an auto-submit based on a short timer, like done for https://github.com/wernight/scruffy-server see around https://github.com/wernight/scruffy-server/blob/master/index.tpl#L128

**Comment by wernight** [comment]
Would you accept PR for this?

**Comment by arnaudroques** [comment]
Although this is a good idea, it may be not so easy to implement.
Actually, when you click on "submit", a new URL is generated for the page.
The URL contains the full diagram text compressed (see http://plantuml.com/pte )

So if we put in place such autosubmit, it means that the full web page is going to be reload, which may be annoying for users (because, for example, the cursor location in the text area could be lost).
A possible option could be to refresh *only* the image url, without refreshing the whole page (I guess that this is your intention anyway).

We are currently really out-of-time, but we could accept a PR if:
- You add also a button to enable/disable "autorefresh"
- You store the current state of this button in some cookie so that users keep their preference about "autorefresh"

Does it sound good to you ?
Thanks!

**Comment by wernight** [comment]
About the URL, you can update it, see https://github.com/wernight/scruffy-server/blob/master/index.tpl#L124
