### ISSUE TITLE
Accept plain text

### ISSUE THREAD

**Issue by yewton** [plantuml/plantuml-server#67]
Hi.

I'm working on [enabling Emacs plantuml-mode to use plantuml-server](https://github.com/skuro/plantuml-mode/pull/63).

If plantuml-server accepted both pte and plain text, such an editor integration might be more easy.
( FYI, [VSCode uses plantuml-server too](https://github.com/qjebbs/vscode-plantuml/blob/7af16683a8625b3061b78425a6f2d331c242efbc/src/plantuml/renders/plantumlServer.ts#L115) )

Does this make sense?

**Comment by arnaudroques** [comment]
Thanks for the suggestion.
Are you thinking about a POST or a GET request for plain text ?

**Comment by yewton** [comment]
I suppose a POST request would be appropriate for that.
The status code of the response would be `201 CREATED`, its body would be some of `image/*` and include `Location` header that indicates the plantuml-text-encoded URL for future GET.

**Comment by arnaudroques** [comment]
Ok, we would like to limit traffic on our server.
So we propose a single request. A new beta version of the server is online.
If you POST some request to http://www.plantuml.com/plantuml/uml with "uml" variable equals to your diagram text (and optionally a "format" equals to "svg") you'll get some PNG/SVG http response.

Example of a very basic usage:
```
<html>
<form action=http://www.plantuml.com/plantuml/uml method=POST>
<textarea name=uml>
@startuml
alice -> bob
@enduml
</textarea>
<!-- format optional and png by default, only png and svg supported--> 
<input name=format type=text value=png>
<input type=submit>
</form>
</html>
```

Will this help ?

**Comment by yewton** [comment]
It works! Thank you 😄 

> we would like to limit traffic on our server

From this point of view, it would be better that making request as `text/plain` and accepting `Content-Encoding: gzip` so that we can avoid to URL encode the body and optionally compress it.
The sequence would be like:
![](http://www.plantuml.com/plantuml/png/NOsz3eCm38JtF8NLFQBjYFepi58L2P0wT771q4WGHy51zEqRcAhUSlBf_DtRj0GTixnuKGeROG_rH1vmWg0SUZ6DSMW5TiKGhRxbK9AVoU_MYbCgWBw0WnIAUrb14iRXsh4VKSxEza-RiHMoegkFenI45adSWCQkMsP6eSW8SD9wOnpt1yWynRZzVpKZzfHip9mR5CCsXVLE7b6gfH_W5m00)

If this makes sense, I'd love to implement myself and make a pull request!


In any case, I will encourage them to use their own PlantUML server 😃 (with docker or jetty-runner ).

**Comment by abulka** [comment]
The ability to POST plain PlantUML text would be great.

Is the beta server with this feature still running?  I just tried `curl -v POST http://www.plantuml.com/plantuml/uml -d "uml=bob--fred"` and had no luck.

Fun fact:  I actually used to be able to POST via the following approach `curl -vX POST http://www.plantuml.com/plantuml/form -d "text=bob--fred"` which still works for my local server but no longer with www.plantuml.com - it seems that the form code has changed recently?  The latest plantuml.com form does plain PlantUML text --> encoded text in javascript, then issues a GET, whereas [the old form](https://github.com/plantuml/plantuml-server/blob/bfb5f3ad159ec09209ea86416ade11bec996d47a/src/main/webapp/index.jsp) did this encoding work on the server, as part of a proper POST endpoint?  

So am I to understant that the old POST endpoint went away and is now coming back, albiet we pass the data in the 'uml' variable rather than the 'text' variable?  And why is https://github.com/plantuml/plantuml-server/ code different to what is deployed on http://www.plantuml.com - is there another repo we should be looking at?

**Comment by HeinrichAD** [comment]
For documentary reasons: It is possible to send the diagram text/code as body via post request to get the desired response.

### Examples

#### Request PNG and save result to test.png
```bash
curl -X POST http://localhost:8080/plantuml/png --data-binary @- -o test.png << EOF
@startuml
Bob -> Alice : hello
@enduml
EOF
```

#### Request SVG with additional header and print response to stdout
It is not necessary but you could also add additional headers like e.g. Content-Type.
```bash
curl -X POST http://localhost:8080/plantuml/svg \      
-H 'Content-Type: text/plain; charset=utf-8' \
--data-binary @- << EOF                       
@startuml
Bob -> Alice : hello
@enduml
EOF
```

#### Request PNG with diagram inside a file
`test.puml`:
```plantuml
@startuml
Bob -> Alice : hello
@enduml
```
```bash
curl -X POST http://localhost:8080/plantuml/png --data-binary @test.puml -o test.png
```

#### Request PNG with `data-raw` instead of `data-binary`
If you do not like the _binary_ in `--data-binary` you can also use `--data-raw`.  
Note: `--data-binary` isn’t just for binary data. It just means that it sends the data completely as-is. No stripping newlines or other changes.
```bash
curl -s -X POST http://localhost:8080/plantuml/png -o test.png --data-raw '@startuml
Bob -> Alice : hello
@enduml'
```
