### ISSUE TITLE
Support POST requests

### ISSUE THREAD

**Issue by evandrocoan** [plantuml/plantuml-server#69]
Because GET requests have a char length limit

```python
from urllib.parse import urlencode
from urllib.request import Request, urlopen

url = 'http://localhost:8080/plantuml/post'
post_fields = {'source': r'@startuml\na --> b\na <-- b\n@enduml'}

request = Request(url, urlencode(post_fields).encode())
answer = urlopen(request).read().decode()
print(answer)
```

Would be useful for internal application as:

1. https://github.com/qjebbs/vscode-plantuml
1. https://github.com/pkucmus/sublime-plantuml

With this they can render the images much faster and can handle big diagrams:

> Plugin supports two renders: `Local` and `PlantUMLServer`.
> 
> Local is the default and traditional way. If you care more about export speed, you should try PlantUMLServer.
> 
> ```text
> Local: 6 documents, 9 digrams, 14 files exported in 24.149 seconds
> PlantUMLServer: 6 documents, 9 digrams, 14 files exported in 1.564 seconds
> ```

![](https://github.com/qjebbs/vscode-plantuml/raw/master/images/auto_update_demo.gif)

**Comment by HeinrichAD** [comment]
For documentary reasons: It is possible to send the diagram text/code as body via post request to get the desired response.
See examples here: https://github.com/plantuml/plantuml-server/issues/67#issuecomment-1616625832

About the second issue:
```
Bad Message 431
reason: Request Header Fields Too Large
```

I can not really reproduce the error with the current version `v1.2023.8`. If the issue is still valid, please open a separate issue including an example how to reproduce it. Please also check/include what you exactly write into the request header fields.
