### ISSUE TITLE
Use PlantUML behind a reverse proxy

### ISSUE THREAD

**Issue by eschaarschmidt** [plantuml/plantuml-server#79]
Hi everyone,

i try to use plantUML behind a reverse proxy and have some problems with it.

My plantuml server ist running at:
http://plantuml.pcf.tld/

The request  for plantuml goes to:
**http://intra.domain.tld/plantuml** which reverse proxys requests to 
**http://plantuml.pcf.tld/**

Direct Requests to png/svg are working, for example:
http://intra.domain.tld/plantuml/png/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000 -> works fine

What is not working are links in the jsp singlepage application.

Whent i try to access: http://intra.domain.tld/plantuml/
it redirects to http://intra.domain.tld/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000 -> which is the wrong context root ("uml" instead of "plantuml").

When i try to access the singlepage application with a direkt request like:
http://intra.domain.tld/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
the page loads, but all links in build against the wrong URL ( it builds the links against http://plantuml.pcf.tld instead of http://intra.domain.tld/plantuml )

I would really like to use the jsp singlepage with the reverse Proxy. I have not found a way to fix this.
The index.jsp gets the host URI from:
 <c:set var="hostpath" value="${scheme}://${pageContext.request.serverName}${port}${contextroot}" />

As the server where plantuml is running is not the same that delivers the webpages, this does not work for my scenario. 

Can you make the baseurl where plantuml is building on configurable or have any advice for me?

**Comment by paddy-hack** [comment]
Found myself in a similar :boat: 

Used the approach from #80 to make the plantuml-server serve on `/plantuml` rather than `/` and  reverse proxying was all good again.

**Comment by HeinrichAD** [comment]
I know this Issue is quite old but I faced the same problem.

If there is a solution in the meantime, please let me know. Perhaps we could add an example in the README.

Situation as above:
1. plantuml-server as docker container
2. nginx server as another docker container which should work as proxy

### Dirty workaround
nginx.config
```nginx
location /plantuml/ {
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    rewrite ^(/plantuml)+/(.*) /plantuml/$2 break;    # the messy part
    proxy_pass http://plantuml-server:8080/;
}
```
docker-compose.yml
```yml
version: '3.3'

services:
  plantuml-server:
    build:
      context: https://github.com/plantuml/plantuml-server.git
      dockerfile: Dockerfile.jetty
      args:
        BASE_URL: plantuml
    image: plantuml/plantuml-server:local
    container_name: plantuml-server
    ports:
      - 8080:8080
```

### The Problem as far as I understood
The main reason for this is that the nginx context path "/plantuml" is only passed through the main page, but the urls inside the web page still use root "/" as context path. This, of course, does not work.
This workaround forced the plantuml container to add "/plantuml" because of its `BASE_URL`. In effect, the original page call would now be `http://myserver.xx/plantuml/plantuml`, which would attempt to load the contents of `http://myserver.xx/plantuml/xyz` internally. To stop this behavior, the rewite forces every call to `http://myserver.xx/plantuml/...` (no multiple "plantuml").
At least this works for me now. But to be honest, it is too dirty.

**Again. If anyone knows of a clean solution, I would greatly appreciate it.**

### Possible Solution?

Maybe it is possible to extend the `hostpath`, where `PROXY_CONTENT_PATH` could be an environment variable?
https://github.com/plantuml/plantuml-server/blob/eae269348f790ad41ae81b5efa3e5aec1157e10d/src/main/webapp/index.jsp#L11
```diff
-"${scheme}://${pageContext.request.serverName}${port}${contextroot}"
+"${scheme}://${pageContext.request.serverName}${port}${PROXY_CONTENT_PATH}${contextroot}" 
```

**Comment by marck-gee** [comment]
I had the same problem. The solution can be found [https://github.com/plantuml/plantuml-server/issues/64](url), and just requires you to add the http-forwarded as a command-line argument. 

Here is my updated docker-config file:

`
version: '3.3'

services:
  plantuml-server:
    image: plantuml/plantuml-server:jetty

    container_name: plantuml
    ports:
      - 8080:8080
    command: --module=http-forwarded
`
