### ISSUE TITLE
Security issue in plantuml server docker image

### ISSUE THREAD

**Issue by PavelSosin** [plantuml/plantuml-server#86]
I installed locally plantuml server as docker image plantuml/plantuml-server:tomcat and start it as http:// localhost:8080
When I investigated the displayed form source I found link "http://plantuml.sourceforge.net"
This link takes me to another domain. It looks like corse issue. Maybe in plantuml/plantuml-server:tomcat plantuml server is packed without proxy?

**Comment by arnaudroques** [comment]
There is a link to http://plantuml.sourceforge.net here  https://github.com/plantuml/plantuml-server/blob/3920af3a913f2e30f4497d12c8b11309e2f2eefd/src/main/webapp/index.jsp#L54

Is this what you are talking about ?
The fact is we should (and will) update to http://plantuml.com

**Comment by PavelSosin** [comment]
If I started plantum server from localhost (as docker container) I can't go outside localhost domain via link in web page. This is simple security requirement. If application uses more then 1 domain I has to go via proxy. Please take cloud deployment scenario into account! This is main productive scenario today.Application can't be deployed to several domains.

**Comment by PavelSosin** [comment]
The solution will be simple: take me to localhost:8080/plantuml/site and redirect to **https**:plantuml.com

**Comment by HeinrichAD** [comment]
For documentation purpose:

There exists two external links inside the PlantUML Server Web Application:

![image](https://github.com/plantuml/plantuml-server/assets/5962361/b9855a64-9871-4894-ad68-dd0540750f20)

1. <https://plantuml.com/>
2. <https://github.com/plantuml/plantuml-server>

Since nowadays all external links use `https` the browsers shouldn't have any security concerns like [Mixed Content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) anymore.

----

Also note: While it is currently not possible to remove the first external link without changing the code yourself, there exists a config.property to remove the GitHub banner (second external link):
https://github.com/plantuml/plantuml-server/blob/294b2a241829855455f6fea3dca03a7d49e9d262/src/main/resources/config.properties#L1-L3

----

Edit: Some nice front-end features like the smiley preview inside the code editor use external recourses (over https).
